root: true

extends:
  - pegasus
  - pegasus/browser
  - plugin:react/recommended
  - plugin:react-hooks/recommended

rules:
  react/react-in-jsx-scope: off
  react/prop-types: off
  react-hooks/rules-of-hooks: error

parserOptions:
  project: tsconfig.eslint.json

overrides:
  - files:
      - '*.ts'
    extends:
      - pegasus/typescript
  - files:
      - scripts/*.js
      - .storybook/*.{js,cjs}
    extends:
      - pegasus/node
  - files:
      - '*.stories.@(js|jsx|ts|tsx)'
    extends:
      - pegasus/typescript
      - plugin:storybook/recommended

settings:
  react:
    version: detect
