root: true

extends:
  - pegasus
  - pegasus/browser
  - plugin:react/recommended
  - plugin:react-hooks/recommended

rules:
  react/react-in-jsx-scope: off
  react/prop-types: off

overrides:
  - files:
      - '*.ts'
    extends:
      - pegasus/typescript
    parserOptions:
      project: tsconfig.json
  - files:
      - scripts/*.js
      - .storybook/*.{js,cjs}
    extends:
      - pegasus/node
    rules:
      no-console: off
  - files:
      - '*.stories.@(js|jsx|ts|tsx)'
    extends:
      - plugin:storybook/recommended
      - pegasus/typescript
    parserOptions:
      project: tsconfig.json

settings:
  react:
    version: detect
